# Generated by Django 2.1.3 on 2019-04-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(max_length=16)),
                ('module', models.CharField(max_length=16)),
                ('user', models.CharField(default='', max_length=16)),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
