# Generated by Django 2.1.3 on 2019-04-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=16, unique=True)),
                ('u_pwd', models.CharField(max_length=16)),
            ],
        ),
    ]
