# Generated by Django 2.1.3 on 2019-06-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobname', models.CharField(max_length=32, unique=True)),
                ('minute', models.CharField(max_length=32)),
                ('hour', models.CharField(max_length=32)),
                ('day', models.CharField(max_length=32)),
                ('month', models.CharField(max_length=32)),
                ('weekday', models.CharField(max_length=32)),
                ('jobcli', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Crontab_Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(default='', max_length=64)),
                ('job_host', models.GenericIPAddressField()),
                ('job_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(max_length=16, unique=True)),
                ('h_ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host_zabbix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('za_ip', models.GenericIPAddressField(unique=True)),
                ('za_action', models.IntegerField()),
                ('za_cpu', models.FloatField()),
                ('za_mem', models.FloatField()),
                ('za_disk', models.FloatField()),
                ('h_extend', models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='hosts.Host')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('hg_id', models.AutoField(primary_key=True, serialize=False)),
                ('hg_name', models.CharField(max_length=16, unique=True)),
                ('hg_h_r', models.ManyToManyField(to='hosts.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=16, unique=True)),
                ('s_type', models.CharField(max_length=16)),
                ('h_server', models.ManyToManyField(to='hosts.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Service_zabbix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('za_ip', models.GenericIPAddressField(unique=True)),
                ('za_mysqld', models.IntegerField(default=999)),
                ('za_nginx', models.IntegerField(default=999)),
                ('za_ewc', models.IntegerField(default=999)),
                ('h_extend', models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='hosts.Host')),
            ],
        ),
        migrations.AddField(
            model_name='crontab',
            name='cron_host',
            field=models.ManyToManyField(to='hosts.Host'),
        ),
    ]
