# Generated by Django 2.1.3 on 2019-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(default='', max_length=64)),
                ('server_host', models.GenericIPAddressField()),
                ('server_status', models.IntegerField()),
            ],
        ),
    ]
