# Generated by Django 2.1.3 on 2019-07-17 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_service_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('conf_name', models.CharField(max_length=64, unique=True)),
                ('conf_path', models.CharField(max_length=64)),
                ('current_ver', models.IntegerField()),
                ('modified_ver', models.IntegerField()),
                ('conf_host', models.ManyToManyField(to='hosts.Host')),
            ],
        ),
    ]
