# Generated by Django 2.1.3 on 2019-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_confd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confd',
            name='current_ver',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='confd',
            name='modified_ver',
            field=models.IntegerField(default=0),
        ),
    ]
