# Generated by Django 2.1.3 on 2019-07-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20190718_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='confd',
            name='conf_service',
            field=models.ManyToManyField(to='hosts.Service'),
        ),
    ]
