# Generated by Django 2.1.3 on 2019-07-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_confd_update_history_conf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confd_update_history',
            name='conf_name',
            field=models.CharField(max_length=32),
        ),
    ]
